basePath: /api
definitions:
  github_com_bulatminnakhmetov_brigadka-backend_internal_service_profile.City:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  github_com_bulatminnakhmetov_brigadka-backend_internal_service_profile.TranslatedItem:
    properties:
      code:
        type: string
      description:
        type: string
      label:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@brigadka.com
    name: API Support
  description: API для сервиса Brigadka
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Brigadka API
  version: "1.0"
paths:
  /profiles/catalog/cities:
    get:
      description: Retrieves a list of available cities
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_bulatminnakhmetov_brigadka-backend_internal_service_profile.City'
            type: array
        "500":
          description: Server error
          schema:
            type: string
      summary: Get Cities
      tags:
      - catalog
  /profiles/catalog/genders:
    get:
      description: Retrieves a catalog of genders with translations
      parameters:
      - description: 'Language code (default: en)'
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_bulatminnakhmetov_brigadka-backend_internal_service_profile.TranslatedItem'
            type: array
        "500":
          description: Server error
          schema:
            type: string
      summary: Get Genders
      tags:
      - catalog
  /profiles/catalog/improv-goals:
    get:
      description: Retrieves a catalog of improv goals with translations
      parameters:
      - description: 'Language code (default: en)'
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_bulatminnakhmetov_brigadka-backend_internal_service_profile.TranslatedItem'
            type: array
        "500":
          description: Server error
          schema:
            type: string
      summary: Get Improv Goals
      tags:
      - catalog
  /profiles/catalog/improv-styles:
    get:
      description: Retrieves a catalog of improv styles with translations
      parameters:
      - description: 'Language code (default: en)'
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_bulatminnakhmetov_brigadka-backend_internal_service_profile.TranslatedItem'
            type: array
        "500":
          description: Server error
          schema:
            type: string
      summary: Get Improv Styles
      tags:
      - catalog
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
